### ISSUE TITLE
Need the output for mesh_format ASAP

### ISSUE THREAD

**Issue by DamienGeneste** [Turbulence-Master/MeshGeneration-Framework#7]
Hello Everyone, 

As we discussed the day before yesterday with Drashti, in our team we need the output (or at least the idea) for the mesh_format. 
To sum up our work, we are doing mesh analysis (using angles in the mesh, ration in the length by width, ...).

In order to simplify our code it should be nice to have a file containing group of 4 neighbouring points (that it is called Cell) mentioning also the cell number. (I hope it is clear enough). 

Someone can tell me who take care of this part?

**Comment by ilkaysolak** [comment]
I do not think you need the output or an output format. You need to know `type mesh_grid(or another name)`. And there should be an array holding actual coordinates. (See https://github.com/Turbulence-Master/MeshGeneration-Framework/blob/master/src/class_mesh.f90)


Mesh will be in an array like `grid(:,:,:)` and most of the time it will be one dimensional. So you will have an input array with the size `grid(1,1,Nz)` or `grid(Nx, 1, 1)`.

People on I/O side should provide read/write routines. So the input of your routines expected to be the output of `read_grid` subroutine or/and `generate_grid`.

**Comment by ilkaysolak** [comment]
Is this resolved?

**Comment by viks4mech** [comment]
Hello Ilkay,

Sorry for the delay in replying, I know this issue's been closed but felt
that it was not answered properly so my mail.

Diana and i worked on 3 formats (.vtk,.dat, .CSV), since at the beginning
we had issues with .vtk so we decided to generate codes for other two.

The VTK format currently in GIT is for normal rectangular grid and it
doesnot work for any other irregular shape. one can see this output in
paraview by opening the file generated by the module.

Other formats we worked on are .dat and .CSV as per you suggestion. There
are no tools or specific format (atleast i couldn't find) for writing files
in .dat and hence i decided to go with the my own.
For CSV, the output data can again be opened  in PARAVIEW for visualization.

I'm attaching the output file that each module generate along with the raw
mesh data given by alvaro's code.

Please note that even though the alvaro's output is for some irregular
shape mesh(NOZZLE i suppose), the .VTK output assumes it to be for
Rectangular shaped and generates the output.
With regards,
Bipin Kumar Singh

**Comment by ilkaysolak** [comment]
I will answer under my earlier message. https://github.com/orgs/Turbulence-Master/teams/impt-2017
